### ISSUE TITLE
SSL Cert rotation on AWS ECS

### ISSUE THREAD

**Issue by davidthor** [architect-team/architect-cli#263]
We recently introduced a first-class integration with [cert-manager](https://cert-manager.io/) for Kubernetes to enable SSL certs to be provisioned and rotated by cert manager without requiring re-deploys. However, we don't yet have a comparable solution for AWS ECS based deployments which cannot rotate certs without redeploys. We plan on integrating with [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/), but don't yet have the work scoped to do so.

If anyone is particularly interested in accelerating this feature, let us know with a 👍 on the issue!

**Comment by ryan-cahill** [comment]
@davidthor we're probably good to close this
